TRUNCATE TABLE packcards CASCADE;
TRUNCATE TABLE deckcards CASCADE;
TRUNCATE TABLE stackcards CASCADE;
TRUNCATE TABLE tradingdeals CASCADE;
TRUNCATE TABLE packs CASCADE;
TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE cards CASCADE;